№Задание 1
Создайте numpy array с элементами от числа N до 0 
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
import numpy as np

In [3]:
A = np.arange(9)
A = A[::-1]
A

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

#Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [5]:
B = A.reshape(3, 3)
B

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [6]:
Diag_sum = np.trace(B)
Diag_sum

12

Задание 3                                   
Решите систему уравнений:                      
4x + 2y + z = 4                                    
x + 3y = 12                     
5y + 4z = -3                        

In [8]:
# x = 4,1,0
# y = 2,3,5
# z = 1,0,4

In [9]:
M = np.array([[4, 1, 0], [1, 3, 0], [0, 5, 4]])
V = np.array([4, 12, -3])
R = np.linalg.solve(M, V)
R

array([ 0.  ,  4.  , -5.75])

In [10]:
# X - 0
# Y - 4
# Z - -5.75

Задание 4                      
Имеется матрица покупок в интернет магазине.                     
Столбец А - id пользователя.                       
Остальные столбцы - количество покупок категорий товаров этим пользователем.

In [12]:
user_stats = np.array (
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ],
)

In [13]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя, 
т.е. поссчитайте косинусное сходство между этим пользователем и всеми пользователями массива.

In [15]:
def cosine(user_stats, next_user_stats):
    #длинны векторов
    user_stats_1 = np.linalg.norm(user_stats)
    next_user_stats_1 = np.linalg.norm(next_user_stats)
    return np.dot(user_stats, next_user_stats)/(user_stats_1*next_user_stats_1)

In [16]:
cosine(user_stats, next_user_stats)

array([0.04688072, 0.23440362, 0.09376145, 0.23440362, 0.09376145,
       0.        , 0.        , 0.14064217, 0.        , 0.        ])

Самые похожие пользователи это пользователь № 3 и № 5.